### ISSUE TITLE
Lookup not called after mv command is executed.

### ISSUE THREAD

**Issue by lpoli** [bazil/fuse#279]
Its a weird issue.
Say I am mounted in `f` folder and there are `a.txt`,  `f/f1/b.txt`.
If I move `b.txt` to `f` folder as `mv f1/b.txt .` given that I am in `f` folder then running `cat b.txt` gives error because it still looks for `b.txt` in `f1` folder.

After some time it itself does lookup and again starts working.

Am I missing something or is it real issue?

**Comment by tv42** [comment]
There is nowhere near enough information here to do much about anything. Most likely explanation is you have a bug in your filesystem implementation. What bug? How would I know, based on what you've told me. Best guess is you're referring to `f1` in `b.txt`'s `Node`, even after that stopped being true.

How do I reproduce your problem?

**Comment by lpoli** [comment]
I've implemented a node structure as;
`type File struct{
    Path string
    Name string
    Size uint64
}` 
And there is similar structure for directory (There are other relevant fields as well).

So the problem is when I execute rename operation within mounted directory then a file is moved from one directory to another but Fuse doesn't forget the node and refers to the same node when accessing from new directory.

 For file read I was using `Path` field which is just the old path because it is the same node so it won't find the file.

If in Rename() function, respective Node was also send just like NewDir node then we could easily update the path and I thought of forking library and changing it but it seems there is no way to send same Node to the function.

Even if I could call `server.DropNode()` then it would work.

I am stuck here and it seems only way is to restructure my code which has grown very big and is risky to do so.

Your suggestion will be valuable.
Thank you.

**Comment by tv42** [comment]
FUSE doesn't forget the Node, it doesn't want to. It's still the same VFS node. Dropping it will cause oddities that just don't need to exist. Adjust what directory a Node belongs to in Rename, when appropriate. Or refuse cross-directory renames with `EXDEV`, and deal with the slowdown when `mv` resorts to copy+delete.

Here's a real-world (not simple) example: https://github.com/bazil/bazil/blob/810cf82680de28f1a758a1fd19492b113203d464/fs/dir.go#L588-L598

**Comment by tv42** [comment]
As for

> I am stuck here and it seems only way is to restructure my code which has grown very big and is risky to do so.

Filesystems are not easy. FUSE does *nothing* to change that, it just means you don't have to *write that code in kernelspace* (and guards against a couple stupid mistakes, by using node and handle IDs instead of pointers in kernel).

In any context, if you typed in a lot of code without understanding the problem domain, there's not much that anyone can tell you to help you. Study the problem domain and slowly fix the code, or don't.
